[package]
name = "remotefs-kube"
version = "0.4.0"
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-kube"
edition = "2024"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["kube-client", "kube"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-kube"
rust-version = "1.89.0"
description = "remotefs implementation for kube"

[dependencies]
chrono = "0.4"
futures-util = "0.3"
k8s-openapi = { version = "0.28", features = ["v1_32"] }
kube = { version = "4", features = ["client", "config", "ws"] }
lazy-regex = "3"
log = "0.4"
remotefs = "0.3"
tar = "0.4"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["fs", "rt"] }
tokio-util = "0.7"

[dev-dependencies]
env_logger = "0.11"
k8s-openapi = { version = "0.28", features = ["v1_32"] }
kube = { version = "4", features = ["client", "config", "runtime", "ws"] }
pretty_assertions = "1"
rand = "0.10"
serde_json = "1"
serial_test = "4"

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.2"

[features]
default = ["find"]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
# tests
integration-tests = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
